### ISSUE TITLE
Korisnici - Izbrisi - Mozemo izbrisati korisnika kojeg trenutno koristimo, tj sami sebe

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#100]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Korisnici - Izbrisi - mozemo izbrisati korisnika kojeg trenutno koristimo,
tj sami sebe

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Pretraziti i odabrati korisnika kojeg trenutno koristimo u aplikaciji
6.  Kliknuti dugme Izbrisi

Dobijeni rezultat:
Mogucnost brisanja aktivnog korisnika

Ocekivani rezultat:
Korisnik ne bi trebao moci obirsati sam sebe ili bilo kojeg drugog korisnika koji je logovan na aplikaciju

**Comment by aklacar1** [comment]
Popravljeno u : aa3f58afe2b02e68a92bee120441622eb539dcf8
