### ISSUE TITLE
Korisnici - Izbrisi - ne vidimo koga smo selektovali za brisanje

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#101]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Korisnici - Izbrisi  - ne vidimo koga smo selektovali za brisanje jer su svi rezultati
pretrage oznaceni u isto vrijeme bez obzira gdje da kliknemo

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Pretraziti korisnike s tim da dobijemo vise rezultata
6.  Kliknuti na nekog od korisnika
7.  Svejedno su uvijek svi prikazani kao selektovani

Dobijeni rezultat:
Uvijek selektovani svi korisnici

Ocekivani rezultat:
Selektovati samo odabrane korisnike

**Comment by aklacar1** [comment]
#97
