### ISSUE TITLE
Potrosaci - Kreiraj - Nemoguce kreirati potrosaca

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#102]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Potrosaci - Kreiraj - Nemoguce kreirati potrosaca
Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Potrosaci u glavnom meniju
4.  Odabrati opciju Kreiraj
5.  Unijeti podatke u sva zahtjevana polja
6.  Kliknuti SPASI
7.  Dobija se validacijska poruka da JMBG nije validan iako je unesen 13-cifreni validan JMBG

Dobijeni rezultat:
Validacijska poruka za JMBG iako je unesen validan broj

Ocekivani rezultat:
Ispravna validacija JMBG polja na formi

**Comment by omarshile** [comment]
Zato je moguce dodati potrosaca ciji je JMBG 0000000000000

**Comment by aklacar1** [comment]
#79
Sto se tice same postavke ovog issue-a ovo je invalid, ali da je kako treba postavljen issue onda je duplicate. Koristi se ista validacija JMBG svugdje.

**Comment by omarshile** [comment]
Ne znam sta je pogresno u postavci problema. Ne mogu kreirati potrosaca jer kada kliknem SPASI DOBIJEM poruku JMBG nije validan

**Comment by omarshile** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11445851/7898636/0d5b9fd6-0706-11e5-8ad8-7a6bacf31728.png)

**Comment by omarshile** [comment]
ne znam zasto je ovo invalid bug
