### ISSUE TITLE
Nije prikazana klasa Ocitanja u Class diagramu

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#103]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema:
Class diagram iz dokumenta: https://github.com/SoftverInzenjeringETFSA/SI2014Tim7/blob/master/Dizajn%20Sistema.pdf
ne sadrzi klasu Ocitanja kao sto je to uradjeno u sistemu:
http://imgur.com/J02RFWu

**Comment by aklacar1** [comment]
Ocitanja je zapravo Vodomjer i VodomjerService, samo preimenovano i izmjenjeno naspravm Class dijagrama.
