### ISSUE TITLE
Korisnici - Izmijeni - Nemogucnost izmjene samo checkbox-a Administrator

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#104]
Komponenta:
JKP Vodovod i Kanalizacija desktop

Commit ID:

bb0e5ca

Opis Problema:
Korisnici - Izbrisi - Nije moguce izmijeniti samo Admin Opcije korisnika, bez da klinkemo u druga polja i spasiti te izmjene

Koraci za reproduciranje problema:
1. Kompajlirati aplikaciju (Run as java application)
2. Prijaviti se u aplikaciju kao admin
3. Kliknuti na opciju Korisnici u glavnom meniju
4. Odabrati opciju Izmijeni
5. Pretraziti i odabrati korisnika
6. Kliknuti checkbox Administrator u sekciji Admin Opcije
7. Nije moguce spasiti napravljene izmjene

Dobijeni rezultat:
Nemogucnost izmjene samo Admin Opcije kod korisnika

Ocekivani rezultat:
Mogucnost izmjene samo Admin Opcije kod korisnika

**Comment by azramahmutovic** [comment]
Ispravljeno
commit id 127367943227f12436565a0b3dabb2bd0782ce74
