### ISSUE TITLE
Nepoklapanje SRS v1.1 i aplikacije oko privilegija kod brisanja potrošača

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#105]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
U SRS v1.1 je rečeno da samo administratori imaju pravo da odaberu opciju brisanja izabranog potrošača, a u aplikaciji to mogu i obični korisnici
SRS v1.1: http://postimg.org/image/g83ktez3n/
Aplikacija: http://postimg.org/image/atuolki1x/ 

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se kao obični korisnik
Otvoriti tab "Potrošači" i izabrati opciju "IZBRIŠI".

**Comment by aklacar1** [comment]
Popravljeno u : aa3f58afe2b02e68a92bee120441622eb539dcf8
