### ISSUE TITLE
Nepoklapanje SRS v1.1 i aplikacije kod ulaza za brisanje potrošača

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#108]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Ulazi navedeni u SRS v1.1 se ne poklapaju sa ulazima u aplikaciji za brisanje potrošača
SRS v1.1: http://postimg.org/image/s41937w2z/
Aplikacija: http://postimg.org/image/atuolki1x/

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se.
Otvoriti tab "Potrošači" i izabrati opciju "IZBRIŠI".

**Comment by aklacar1** [comment]
Popravljeno u  : aa3f58afe2b02e68a92bee120441622eb539dcf8

S tim da je ovaj nacin brisanja prenesen na pretragu i pregled
