### ISSUE TITLE
Potrosaci - Izbrisi - Ne vidi se odabrani potrosac

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#109]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Potrosaci - Izbrisi – Nakon pretrage koja ima vise rezultata, ne vidi se odabrani potrosac

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Potrosaci u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Pretraziti potrosace da se dobije vise rezultata
6.  Kliknuti na bilo kojeg potrosaca
7.  I dalje su svi selektovani

Dobijeni rezultat:
Uvijek su selektovani svi potrosaci

Ocekivani rezultat:
Selektovati samo odabranog potrosaca
![untitled](https://cloud.githubusercontent.com/assets/11445851/7898669/7c99b972-0707-11e5-8590-4234228ecce5.png)

**Comment by azramahmutovic** [comment]
Ispravljeno
commit 35277a129bd8656d69058b2ff50d24d9e9a2eb95
