### ISSUE TITLE
Potrosaci - Izbrisi - Potrosac se ne brise

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#110]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Potrosaci - Izbrisi - Potrosac se ne brise

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Potrosaci u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Pretraziti potrosace da se dobije vise rezultata
6.  Kliknuti na bilo kojeg potrosaca
7.  Kliknuti dugme Izbrisi
8.  Dobije se poruka da je uspjesno obrisan potrosacki racun kao na slici ispod
9.  Potrosac se i dalje nalazi u bazi i prikazuje se prilikom pretrage potrosaca

Dobijeni rezultat:
Potrosac nije obrisan

Ocekivani rezultat:
Obrisati selektovanog potrosaca

![untitled](https://cloud.githubusercontent.com/assets/11445851/7898682/ed2135a8-0707-11e5-922e-ed6dc1817ad2.png)

**Comment by aklacar1** [comment]
Nije bug i duplicate je ranijeg jednog, ali to je nevazno kad je invalid.

**Comment by omarshile** [comment]
kako je invalid ako nije obrisan potrosac a dobio sam poruku da jeste :D

**Comment by omarshile** [comment]
ne znam sta je invalid, samo odradi pretragu potrosaca da dobijes vise rezultata, odaberi jednog, klikni izbrisi i dobijes poruku, a u bazi nema nikave promjene. 

Ovo djeluje kao critical bug

**Comment by aklacar1** [comment]
Cilj je da ostane potrosac u bazi, tj. da se ne izbrise. Mozes ga izbrisati i obnoviti, vec je jednom ovo isto bilo postavljeno, tako da cak i da nije invalid bio bi duplicate.
