### ISSUE TITLE
Pretraga vodomjera ne radi kod brisanja podataka o potrošnji

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#111]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Ne radi pretraga vodomjera kod brisanja podataka o potrošnji.
Pri pokušaju pretrage vodomjera koji se nalazi u bazi podataka, prikaže se prazna lista vodomjera.

Aplikacija: 
1.) Unesena je potrošnja za vodomjer:
http://postimg.org/image/oxswc360d/
2.) Taj isti vodomjer nije pronađen pri brisanju podataka o potrošnji
http://postimg.org/image/pko68f1gv/

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se.
Otvoriti tab "Očitanja", izabrati opciju "IZBRIŠI" i pretražiti vodomjere.

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716e.
