### ISSUE TITLE
Ocitanja - Unesi - Nakon dodavanja novog ocitanja, klikom na drugi izbor vodomjera ce selektovati sve vodomjere

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#112]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Ocitanja - Unesi - Nakon dodavanja novog ocitanja, klikom na drugi izbor vodomjera ce selektovati sve vodomjere

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Ocitanja u glavnom meniju
4.  Odabrati opciju Unesi
5.  Odabrati vodomjer i unijeti podatke za period i stanje vodomjera
6.  Kliknuti SPASI
7.  Zatvoriti prozor poruke o uspjesno dodanom ocitanju
8.  kliknuti na neodabrani vodomjer
9.  Oba izbora postanu selektovana (slika ispod)

Dobijeni rezultat:
Selektovani svi dostupni vodomjeri

Ocekivani rezultat:
Selektovati samo odabrani vodomjer

![untitled](https://cloud.githubusercontent.com/assets/11445851/7898768/039defa8-070b-11e5-83b2-4ffff5994dd9.png)

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716e.
