### ISSUE TITLE
Ocitanja - Izbrisi - Brisanje ocitanja kojeg ne vidimo - nejasna poruka

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#113]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Ocitanja - Izbrisi - Brisanje ocitanja kojeg ne vidimo

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Ocitanja u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Odabrati vodomjer i unijeti podatke za period za koji smo pravili ocitanja
6.  Kliknuti IZBRISI
7.  Dobijemo poruku kao na slici ispod

Dobijeni rezultat:
Poruka da smo obrisali odabrano ocitanje, a nismo imali priliku da ga odaberemo. Ne znamo koje je ocitanje odabrano iz unesenog mjeseca i godine

Ocekivani rezultat:
Obrisati odabrano ocitanje ili sva ocitanja za odabrani mjesec. Korisnik treba znati sta je obrisao.

![untitled](https://cloud.githubusercontent.com/assets/11445851/7898794/72a583a6-070c-11e5-8889-93d4ee0ba1c2.png)

**Comment by omarshile** [comment]
vidio sam da se moze dodati samo jedno ocitanje za jedan mjesec pa vjerovatno to ocitanje obrise. Poruka je misleading

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716e.
