### ISSUE TITLE
Ne validira se starost datuma pri generisanju računa

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#114]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Pri generisanju računa za određeni vremenski period, ne vrši se provjera da li je početni datum 
stariji od krajnjeg datuma.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se.
Otvoriti tab "Računi", izabrati opciju "GENERIŠI", unijeti početni i krajnji datum i kliknuti na "SPASI".

**Comment by aklacar1** [comment]
Ispravljeno u : 5372ae86e07be662a3f8b387f4f89a51512d56fe
