### ISSUE TITLE
Ocitanja - Izbrisi - Selektovani svi vodomjeri

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#115]
Komponenta:
JKP Vodovod i Kanalizacija desktop

Commit ID:

bb0e5ca

Opis Problema:
Ocitanja - Izbrisi- Nakon brisanja ocitanja, klikom na drugi izbor vodomjera ce selektovati sve vodomjere

Koraci za reproduciranje problema:

```
Kompajlirati aplikaciju (Run as java application)
Prijaviti se u aplikaciju kao admin
Kliknuti na opciju Ocitanja u glavnom meniju
Odabrati opciju Izbrisi
Odabrati vodomjer i unijeti podatke za period koji postoje ocitanja
Kliknuti Izbrisi
Zatvoriti prozor poruke o uspjesno dodanom ocitanju
Kliknuti na neodabrani vodomjer
Oba izbora postanu selektovana (slika ispod)
```

Dobijeni rezultat:
Selektovani svi dostupni vodomjeri

Ocekivani rezultat:
Selektovati samo odabrani vodomjer

![untitled](https://cloud.githubusercontent.com/assets/11445851/7898817/fa4e36c2-070c-11e5-86ae-a9d6533b2816.png)

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716e.
