### ISSUE TITLE
Racuni - Generisi - Nista se ne desava kada se klikne dugme GENERISI

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#116]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Racuni - Generisi - Nista se ne desava kada se klikne dugme spasi

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Racuni u glavnom meniju
4.  Odabrati opciju Generisi
5.  Odabrati pocetni i krajnji datum za koji postoje ocitanja
6.  Kliknuti GENERISI
7.  Nista se ne desi

Dobijeni rezultat:
Nista

Ocekivani rezultat:
Bilo kakva informativna poruka ili poruka o nastaloj gresci

**Comment by aklacar1** [comment]
Popravljeno u : 7801d6b021237801e8fe2033e18b1afc4b641ad4
