### ISSUE TITLE
Racuni - Pretrazi - Nista se ne desi kada kliknemo dugme Pregledaj

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#117]
Komponenta:
JKP Vodovod i Kanalizacija desktop

Commit ID:

bb0e5ca

Opis Problema:
Racuni - Pretrazi - Nista se ne desava kada se klikne dugme Pregledaj

Koraci za reproduciranje problema:

```
Kompajlirati aplikaciju (Run as java application)
Prijaviti se u aplikaciju kao admin
Kliknuti na opciju Racuni u glavnom meniju
Odabrati opciju Pretrazi
Ne unositi nikakve podatke za pretragu
Kliknuti Pregledaj
Nista se ne desi
```

Dobijeni rezultat:
Nista

Ocekivani rezultat:
Bilo kakva informativna poruka ili poruka o nastaloj gresci

**Comment by aklacar1** [comment]
Ispravljeno u : 4a9412d259261637b1cfc392773581d44d53fa2d
