### ISSUE TITLE
vodomjer

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim7#17]
Nemate definisan enitet vodomjer, a imate prikazivanje i pretragu. Za vodomjer se unose stanja u trenutku očitanja, na osnovu kojih se računa potrošnja.

**Comment by aklacar1** [comment]
Definisan, samo sa minornim greskama, ispravljeno (Sifra potrošača je zapravo šifra vodomjera)
Za vodomjer se samo sada unosi potrošnja po mjesecu i godini
