### ISSUE TITLE
Greška pri kompajliranju

### ISSUE THREAD

**Issue by ekurtanovi3** [SoftverInzenjeringETFSA/SI2014Tim7#30]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: cb5ff018cdcb55ff9e91dd23a39f3b831811c719

Opis problema: Prilikom kompajliranja javlja se greška http://pokit.org/get/img/72957f9b3bcacae328d84006a16a8aa0.jpg

Koraci za reproduciranje problema:
1. Kompajlirati aplikaciju (Run as java application)

**Comment by aklacar1** [comment]
Ima li vise informacija ? Jel ti radio internet ? Jesi li build projekat prije toga ? Jer pokretanje aplikacije radi : http://prntscr.com/793p0p 
Gdje su tacno greske ? 

Ako su greske u Renderer i Comparator paketu zbog override, to je do Jave, jer neke verzije Jave ne podrzavaju Override koji je tu potreban :
http://stackoverflow.com/questions/8220786/java-eclipse-override-error

**Comment by aklacar1** [comment]
Greska ispravljena : Core Java compiler postavljen na verziju 1.6
9ac7199167395ac29ea4b045da0cf418f418febf
