### ISSUE TITLE
Greške pri kompajliranju

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#42]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167

Opis problema: Prilikom kompajliranja javljaju se sljedeće greške: http://pokit.org/get/?c1d91f9008602dad15ed2d842293957a.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)

**Comment by aklacar1** [comment]
Ovaj bug je popravljen u datom Commit-u : http://prntscr.com/79dxyn 
Onog trenutka kad se uradi prvi build, verzija compilera se postavi na 1.6 koji prepravlja sve bugove uzrokovane u Eclipse sa  @Override anotacijom

Referenca : #30
Commit fix : 9ac7199167395ac29ea4b045da0cf418f418febf
