### ISSUE TITLE
Validacija imena potrosaca nije uradjena

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#43]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija imena potrosaca.
http://i.imgur.com/nNbe4Cg.png - Prolazi dodavanje nevalidnog potrosaca.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti znakove ili brojeve u polje imena potrosaca.

**Comment by azramahmutovic** [comment]
Ispravljeno
Commit ID: 127367943227f12436565a0b3dabb2bd0782ce74

**Comment by azramahmutovic** [comment]
Ispravljeno
zabranjen unos praznih polja i dozvoljen samo unos slova i crtice izmedju imena
commit 1f56ac7762394ba85e37c0b6d00333171334b4c2
