### ISSUE TITLE
Validacija prezimena potrosaca nije uradjena

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#44]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija prezimena potrosaca.
http://i.imgur.com/nNbe4Cg.png - Prolazi dodavanje nevalidnog potrosaca.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti znakove ili brojeve u polje prezimena potrosaca.

**Comment by aklacar1** [comment]
#43

**Comment by azramahmutovic** [comment]
ispravljeno
zabranjen unos praznih polja i dozvoljen samo unos slova i crtice
commit id 1f56ac7762394ba85e37c0b6d00333171334b4c2
