### ISSUE TITLE
Validacija adrese potrosaca nije uradjena

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#45]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema: Nije uradjena validacija imena adrese potrosaca. Sljedeci format prolazi:
http://i.imgur.com/PaN8YY4.png

Koraci za reproduciranje problema:
Pokrenuti aplikaciju. Logirati se. Unijeti podatke(u ovom slucaju ime adrese kao na slici iznad).

**Comment by aklacar1** [comment]
#43

**Comment by azramahmutovic** [comment]
Ispravljeno
zabranjen unos samo praznih polja
adresa moze sadrzavati samo slova, brojeve, space i crticu(-)
commit 1f56ac7762394ba85e37c0b6d00333171334b4c2
