### ISSUE TITLE
Validacija broja telefona potrosaca nije uradjena

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#46]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija broja telefona potrosaca.
http://i.imgur.com/vk4RKr1.pngg - Prolazi dodavanje nevalidnog potrosaca.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti format telefona xxx/xxx-xxxx.

**Comment by aklacar1** [comment]
#43

**Comment by aklacar1** [comment]
#43

**Comment by azramahmutovic** [comment]
ispravljeno
dozvoljeni formati za telefon 0xx/xxx-xxx i 0xx/xxx-xxxx
commit id 1f56ac7762394ba85e37c0b6d00333171334b4c2
