### ISSUE TITLE
Vizuelni bug- afrikati(slova š,č,ć) se ne prikazuju kako treba na tabu "Računi"

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#47]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Afrikati u tekstovima labela se ne prikazuju.
http://i.imgur.com/NZJ4g6S.png - Labele nisu ispravno napisane.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Kliknuti na tab "Računi".

**Comment by aklacar1** [comment]
Ispravljeno u : c1dfab16f9e9a6d2d5d8361c3473664738b60e30
