### ISSUE TITLE
Nije uradjena validacija imena korisnika

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#48]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija imena korisnika.
http://i.imgur.com/tUX4tHh.png - Prolazi dodavanje nevalidnog korisnika. U ovom slucaju sam unio whitespace " " kao ime korisnika.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti znakove,brojeve ili whitespace u polje imena korisnika.

**Comment by azramahmutovic** [comment]
Ispravljeno
Commit ID: 127367943227f12436565a0b3dabb2bd0782ce74
