### ISSUE TITLE
Odjava - neusaglašenost sa SRS-om

### ISSUE THREAD

**Issue by ekurtanovi3** [SoftverInzenjeringETFSA/SI2014Tim7#49]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Ne postoji dugme za odjavu opisano u SRS-u
http://pokit.org/get/img/3dd2d9e690769c325488f1f21f112d7c.jpg - SRS
http://pokit.org/get/img/8d7485ea5614e372ba95cef5d475f21b.jpg - aplikacija

Koraci za reproduciranje problema:
1. Kompajlirati aplikaciju (Run as java application)
2. Unijeti podatke i logirati se

**Comment by aklacar1** [comment]
Popravljeno u : 5c6245bd0600610bbd5a7b21fcfe3c1be866d55d
