### ISSUE TITLE
Nije uradjena validacija adrese korisnika

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#51]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija adrese korisnika.
http://i.imgur.com/QXCrIVn.png - Prolazi dodavanje nevalidnog korisnika.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti znakove,brojeve ili prazna mjesta u polje adrese korisnika.

**Comment by aklacar1** [comment]
#48

**Comment by azramahmutovic** [comment]
Ispravljeno
Commit ID: 127367943227f12436565a0b3dabb2bd0782ce74
