### ISSUE TITLE
Nije uradjena validacija telefona korisnika

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#52]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija telefona korisnika.
http://i.imgur.com/QXCrIVn.png - Prolazi dodavanje nevalidnog korisnika. Format xxx/xxx-xxx nije podrzan.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti broj iza crte u polju telefon kod unosa korisnika.

**Comment by aklacar1** [comment]
#48

**Comment by azramahmutovic** [comment]
Ispravljeno
da podrzava samo formate 0xx/xxx-xxx i 0xx/xxx-xxxx
commit 940245a9c7c37a0896accf98e08f31585f363e56
