### ISSUE TITLE
Nije uradjena validacija e-maila korisnika

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#53]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija e-maila korisnika.
http://i.imgur.com/QXCrIVn.png - Prolazi dodavanje nevalidnog korisnika.
E-mail prolazi za format na slici.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Unijeti niz znakova sa slike u polje e-mail kod unosa korisnika.

**Comment by aklacar1** [comment]
#48

**Comment by mkenan** [comment]
Ispravljeno u commit ID : 6830d6faeb4f2fc477600b0c032ff2ea9235a09b
