### ISSUE TITLE
Validacija datuma zaposlenja korisnika nije uradjena

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#54]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Validacija datuma zaposlenja korisnika nije uradjena
http://i.imgur.com/QXCrIVn.png - Prolazi dodavanje nevalidnog korisnika.
NULL vrijednost je moguca za datum zaposlenja. 
Takodjer, moguce je staviti datum zaposlenja 2018. godine, iako je 2015. godina.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Otvoriti tab za unos korisnika i dodati korisnika bez unosa datuma zaposlenja.

**Comment by aklacar1** [comment]
#48

**Comment by azramahmutovic** [comment]
Ispravljeno
Commit ID: 127367943227f12436565a0b3dabb2bd0782ce74
