### ISSUE TITLE
Nije uradjena validacija username-a korisnika

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#56]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Nije uradjena validacija username-a korisnika.
http://i.imgur.com/QXCrIVn.png - Prolazi dodavanje nevalidnog korisnika.
U ovom slucaju je unesen " " kao username korisnika.

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti username i password. Logirati se.
Otvoriti tab za unos korisnika, unijeti " " kao username korisnika.

**Comment by aklacar1** [comment]
#48

**Comment by azramahmutovic** [comment]
Ispravljeno
Username mora imati više od 4 karaktera i može sadržavati brojeve, slova i specijalne znakove - i _
Commit ID: 127367943227f12436565a0b3dabb2bd0782ce74
