### ISSUE TITLE
Izmjena korisnika - Nedostaju podaci u poljima

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#60]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Kod očitavanja podataka korisnika u prozoru za izmjenu podataka o korisniku, u dijelu "podaci o kontaktu" polje za broj telefona ne bude popunjeno.
http://pokit.org/get/?71c8ff42b39d7e41030416f1a4b61858.png

Koraci za reproduciranje problema:

```
Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Korisnici, pa onda Izmjeni
Pretraziti korisnika
Odabrati korisnika iz liste
```

**Comment by aklacar1** [comment]
Bug sami nije u prikazu korisnika, nego sto se prilikom izmjene doda prazno polje u broj telefona korisnika, sto sprijecava ispis broja telefona (a ovo utice na prikaz, jer su prazna polja zabranjena). Oznaceno kao bug.

**Comment by azramahmutovic** [comment]
Ispravljeno
Commit ID: 7ef7a7cf8e15fe878332b08b48f0e55fc6a7d243
