### ISSUE TITLE
Ne postoji dugme koje omogućava izlaz(log out) iz aplikacije

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#61]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Ne postoji dugme(button) koje omogućava izlaz(log out) iz aplikacije

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se

**Comment by deancupovic** [comment]
Duplikat kojeg issue-a?

**Comment by aklacar1** [comment]
Referenca : #49
