### ISSUE TITLE
Izmjena potrošača - Nedostaju podaci u poljima 

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#62]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Kod očitavanja podataka potrosaca u prozoru za izmjenu podataka o potrošaču, u dijelu "lični podaci" polje za broj telefona ne bude popunjeno.
http://pokit.org/get/?ca1e577ce968dbe0153df37ad9eecc74.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Potrošače, pa onda Izmjeni
Pretraziti potrošače
Odabrati potrošača iz liste

**Comment by aklacar1** [comment]
Pitanje : Da li je polje za broj telefona popunjeno u bazi podataka (sa max 10 cifara)?
http://prntscr.com/79h9rt

**Comment by aklacar1** [comment]
Bug sami nije u prikazu potrosaca, nego sto se prilikom izmjene doda prazno polje u broj telefona potrosaca, sto sprijecava ispis broja telefona (a ovo utice na prikaz, jer su prazna polja zabranjena). Oznaceno kao bug.

**Comment by azramahmutovic** [comment]
Ispravljeno
izbrisano prazno polje na kraju brojeva telefona, time je ispravljen i prikaz
commit id 08015fd4fbe0fd383a7de49746b0f1d35f213108
