### ISSUE TITLE
Kreiranje računa ne radi

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#63]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Nakon unosa datuma i klika na drugme "Spasi" se ne dešava ništa. Baza provjerena, ne generiše se novi račun.
http://pokit.org/get/?85a41c25840732049bbd0736037814d4.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Računi, pa onda Generiši
Unos početnog i krajnjeg datuma
Klik na spasi

**Comment by aklacar1** [comment]
popravljeno u : aa3f58afe2b02e68a92bee120441622eb539dcf8
