### ISSUE TITLE
Brisanje potrošača

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#64]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Potrošač kojeg pokušamo da izbrišemo ostaje u bazi i listi korisnika u aplikaciji, iako messagebox govori da je potrošački račun izbrisan.
http://pokit.org/get/?3cbcf03a2bdab2393b7cb3f88195ef49.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Potrošači, pa onda Izbriši
Pretražiti korisnike
Odabrati korisnika
Klik na dugme "izbriši"

**Comment by aklacar1** [comment]
Nije greska, cilj programa je bio da ovako radi za potrosaca.

**Comment by deancupovic** [comment]
Nije jasno. Kako mislite cilj je da radi ovako. Da ne obriše potrošača a prikaže poruku da je obrisan?

**Comment by aklacar1** [comment]
Nas originalni SRS je sadrzavao opciju da se u potpunosti obriše potrošač iz baze. Međutim ste nam vi rekli da je bolja praksa za potrošača da ostane u bazi podataka, ali da je sakriven od pretrage i slicno. Samim tim smo mi implementirali da se potrošač samo prividno briše iz baze, te da ga je moguće vratiti poslije na isti naćin na koji je izbrisan, a i naći preko pretrage kad pretražujemo potrošače po kategorijama u kojima spada i kateogorija obrisanih/sakrivenih potrošača. Tako da je cilj samog programa da prilikom brisanja potrošača samo zamjeni tag potrošača hidden na true, i ispiše da je potrošač izbrisan(prividno).
