### ISSUE TITLE
Izmjena očitanja

### ISSUE THREAD

**Issue by egazetic1** [SoftverInzenjeringETFSA/SI2014Tim7#65]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Kada odaberemo vodomjer u lijevom groupbox-u, na desnom groupbox-u se ne očitavaju podaci za određeni vodomjer.
http://pokit.org/get/?79a7eabb50ad8c45965e23b82d5fc8e1.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Očitanja i Izmijeni
Unos šifre očitanja kojeg želimo izmijeniti
Odabir vodomjera

**Comment by aklacar1** [comment]
Nije greska. Postoji mnogo ocitanja za svakog korisnika, cilj je bio da se dozvoli direktna izmjena, a zbog jako malo podataka za prikazivanje, nisam vidio potrebu da prikazem prijasnje ocitanje pri izmjeni. Jedini nacin za prikaz ocitanja bio bi da se unese datum, a to bi znacilo samo jedno polje da prikazemo koje se i onako treba mijenjati sto je jako nepotrebno.

**Comment by deancupovic** [comment]
Zašto vam onda služi box "Izmjeni očitanje"?

**Comment by aklacar1** [comment]
Pa mouće je promjeniti očitanje (u slučaju da smo pri unosu očitanja pogriješili), samo se ne upisuje stara vrijednost za izmjenu očitanja.
Recimo ako je slučaj sljedeći :

Postoji očitanje za :
Potrošač : A
Mjesec : 2
Godina : 2010
Potrošnja : 100

Prilikom izmjene, potrebni su podatci za potrošača, mjesec i godinu i dodatno je potrebno da unesemo novu potrošnju. Ali smatramo kako je to samo jedno polje koje se mijenja, onda da je nepotrebno da prikazujemo da je potrošnja bila 100, kad već namjeravamo napraviti izmjenu potrošnje na neku novu vrijednost.

U toku izmjene unijeli bi nove podatke, recimo da je potrošnja 120, i dobili bi :
Potrošač : A
Mjesec : 2
Godina : 2010
Potrošnja : 120

Naravno mozemo prepraviti da se vidi staro ocitanje prije unosa novog.

**Comment by unReaLaneS** [comment]
Popravljeno u commit-u id: 2ac7b393be5e00fad829aadd61b2bf28b37dda34
