### ISSUE TITLE
Opcija: Tip potrosaca

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#66]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Problem se nalazi na formi za unos licnih podataka potrosaca i unosa podataka o usluzi.  Ukoliko se greskom odabere opcija "tip potrosaca: s vodomjerom" i klikne na polje za unos "Sifra vodomjera", nije moguce vratiti tip potrosaca na "pausalni" jer ukoliko polje "Sifra vodomjera" ostane prazno, prikazuje se greska "Unesite sifru vodomjera"  i nije moguce spasiti podatke. 
Koraci za nastanak greske su oznaceni brojevima na sljedecoj slici: 

http://pokit.org/get/?8fd24a8356e2c68bba0b6b8bfc1e0eec.jpg

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Na pocetnom ekranu, unijeti podatke potrosaca, podatke o usluzi(odabrati Tip potrosaca: s vodomjerom, ostaviti prazno polje Sifra vodomjera i vratiti se na opciju Tip potrosaca: pausalni)

Dobijeni rezultat:
-Nije moguce spasiti podatke, i greska "Unesite sifru vodomjera" ostaje iako je odabran pausalni tip potrosaca.

Ocekivan rezultat:
-Uspjesno spasavanje podataka

**Comment by aklacar1** [comment]
Jeste bug, ali nisam siguran da li spada u duplikaciju ostalih bugova vezanih za validaciju potrošača, jer je i ovo problem validacije (tj. ne radi validacija kako treba).

**Comment by ensarmuratovic** [comment]
Ja sam pregledao ostale bugove, i nisam nasao slican,moze se desiti da sam fulio. Jest problem i validacije ali je po meni bug jer se ne moze ostaviti zeljena opcija, osim ako uneses sifru vodomjera pa se onda vratis na prvu opciju. Normalnom korisniku bi to bio problem ukoliko urasi drugacije. Kako god l,trebalo bi se nastimat :)

**Comment by azramahmutovic** [comment]
Ispravljeno
pomjerila validaciju sa focusLost na button
commit 1f56ac7762394ba85e37c0b6d00333171334b4c2
