### ISSUE TITLE
Dodavanje ocitanja radi za potrosace kojima je atribut "hidden" stavljen na 1(true)

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#67]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Za unesenog potrosaca sa vrijednoscu atributa hidden 1 moguce je kreirati ocitanje. Ne bi trebalo moci izabrati tog potrosaca s tom sifrom vodomjera.

http://i.imgur.com/Bhe5HeM.png - potrosac
http://i.imgur.com/q1Uu1ss.png - ocitanje

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se.
Na početnom ekranu kreirati potrosaca.
Na početnom ekranu izabrati opciju "Očitanja".
Unos šifre vodomjera potrosaca kojeg smo unijeli.
Unijeti ocitanje vodomjera.

**Comment by unReaLaneS** [comment]
Popravljeno u commit-u id: 2ac7b393be5e00fad829aadd61b2bf28b37dda34
