### ISSUE TITLE
Dodavanje ocitanja radi za potrosace kojima je atribut "aktivnost" stavljen na 0(false/inaktivan)

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#68]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Za unesenog potrosaca sa vrijednoscu atributa aktivnost 0(neaktivnog) moguce je kreirati ocitanje. Ne bi trebalo moci izabrati tog potrosaca za dodavanje ocitanja.

http://i.imgur.com/eo90xuh.png - potrosac
http://i.imgur.com/CdZnq2c.png - ocitanje

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se.
Na početnom ekranu kreirati inaktivnog potrosaca.
Na početnom ekranu izabrati opciju "Očitanja".
Unos šifre vodomjera potrosaca kojeg smo unijeli.
Unijeti ocitanje vodomjera.

**Comment by unReaLaneS** [comment]
Popravljeno u commit-u id: 2ac7b393be5e00fad829aadd61b2bf28b37dda34
