### ISSUE TITLE
Dugme za spasavanje izmjena nefunkcionalno 

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#69]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Kada odaberemo korisnika cije podatke zelimo da editujemo i ako je u startu odabran tip potrosaca : "Sa vodomjerom", ako par puta predjemo iz jednog tipa u drugi tj. odaberemo jedan pa drugi radio button dugme "Spasi" se zaglavi i ne mozemo ga kliknuti dok ne odaberemo ponovo korisnika za edit.
http://pokit.org/get/?76b9f9afd47f54a2a83af48d9fac181d.jpg 
Na slici se moze vidjeti da dugme ne izgleda kako bi trebalo izgledati ukoliko se moze kliknuti:
http://pokit.org/get/?369bca6218bf71839334fbbf28aeea5f.jpg - Normalan izgled dugmeta

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Potrosaci i Izmijeni
Biramo korisnika koji je tip potrosaca "Sa vodomjerom"
Biramo "Pausalni" i birsemo podatke iz vodomjera
Potom ponovo biramo "sa vodomjerom" i jos jednom "pausalni"
Dugme za spasavanje promjena postaje nefunkcionalno

**Comment by aklacar1** [comment]
#66
