### ISSUE TITLE
Dodavanje Potrosaca - Javljanje errora da je korisnik u sistemu, medjutim nije ga moguce pronaci

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#70]
Komponenta: JKP Vodovod i Kanalizacija desktop
Commit ID: 9ac7199

Opis problema:
Pri kreiranju novog korisnika javlja se error da korisnik vec postoji u sistemu:
http://pokit.org/get/?eaf81fd0e7e6475df8f6ca7df29cb776.jpg
Medjutim kada pretrazujemo potrosace ne pronalazi potrosaca
http://pokit.org/get/?0ab7c3e102a8140b85b0f19527f21e58.jpg

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Unosimo podatke koji se mogu vidjeti u screenshotu i pokusavamo dodati korisnika
Nakon toga biramo Pretrazi gdje u polje ime unosimo ime naseg potrosaca
Nakon toga vidimo da se nas potrosac ne nalazi medju potrosacima

**Comment by aklacar1** [comment]
Moze li se taj potrosac pronaci kroz "Skriveni"  ili "Svi" ili "Sa vodomjerom" kategorijom (jer ako je isti potrosac u bazi ili arhiviran ili sa vodomjerom, onda ga i ne mozes naci ako pretrazujes "Pausalni" kategoriju)? Razlog sto pitam ovo je : 
Pri brisanju potrosaca u sistemu ostaje isti potrosac, tj. samo je prividno izbrisan. Tako da to sto javlja u tom slucaju da potroji potrosac je tacna informacija, a isto tako moze postojati u "Sa vodomjerom" kategoriji, a ne "Pausalni".
