### ISSUE TITLE
Unos korisnika- errori nisu usaglaseni sa poljima za unos

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#71]
Komponenta: JKP Vodovod i Kanalizacija desktop
Commit ID: 9ac7199

Opis problema:
Za prazno polje ime: kod unosa novog korisnika javlja se error : "Unesite prezime korisnika":
http://pokit.org/get/?b18c94d8fe978160025db78cf531e662.jpg
Za prazno polje prezime: kod unosa novog korisnika javlja se error : "Unesite ime korisnika":
http://pokit.org/get/?42aae86474e55c52616fbf7dded3ca80.jpg
Error se javlja ustvari tako sto se prikazuje error za prethodno polje na kome smo se nalazili, dakle ako smo prvo bili na polju Prezime koje je bilo prazno a potom kliknuli na polje ime , pokazati ce nam se error za polje prezime

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
U Gornjem meniju biramo opciju "Korisnici" 
Nakon toga otvara se tab za dodavanje Korisnika
Kada odaberemo textbox (koji je prazan u tom momentu) za ime korisnika javlja se error za unos imena korisnika
Kada odaberemo textbox (koji je prazan u tom momentu) za prezime korisnika javlja se error za unos imena korisnika
Ako nakon toga ponovo odaberemo polje za unos imena javiti ce nam se error za unos imena korisnika

**Comment by aklacar1** [comment]
Ovo nije greska, jer je sadasnja validacija tipa : On Focus Lost , sto cemo mozda i izmjeniti. A inace ako gledamo kao gresku onda je duplicate : #48 i #50
