### ISSUE TITLE
Brisanje korisnika - javljanje errora koji nema smisla za ovu komandu

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#72]
Komponenta: JKP Vodovod i Kanalizacija desktop
Commit ID: 9ac7199

Opis problema:
Pri pokusaju brisanja korisnika javlja se error : "JMBG nije ispravan", koji nema smisla na ovome prozoru 
http://pokit.org/get/?ba39a7fa84a861eb8f27624be05f9086.jpg

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
U meniju biramo Korisnici
Potom biramo brisanje korisnika 
Kada pokusamo obrisati korisnika, pritiskom na dugme Izbrisi javlja se error da JMBG nije validan

**Comment by aklacar1** [comment]
Nije greska, to se polje inace ne pojavljuje, to postoji samo zato sto sam napravio admin kojeg ne zelim da je moguce izbrisati pa sam mu postavio nevalidan JMBG kao vid zabrane brisanja :) pretpostavljam da si pokusala izbrisati admin acc, ili dodala direktno u bazu nekog od ostalih sa netacnim JMBG

Nije potrebna tu validacija, ali kako u normalnom radu samog programa se nece nikad pojaviti osim prilikom pokusaja brisanja glavnog korisnika : "admin", ne vidim razlog za izmjenu istog. Moram staviti invalid za ovo jer nije bug, tj. upravo suprotno : validacija JMBG radi :)
