### ISSUE TITLE
Unos potrosaca - format imena i prezimena nije validiran

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#73]
Komponenta: JKP Vodovod i Kanalizacija desktop
Commit ID: 9ac7199

Opis problema:
Ime i prezime se mogu unjeti u bilo kakvom formatu dok god se sastoje samo iz slova, dakle moguce je unjeti korisnika sa ovakvim imenom :
http://pokit.org/get/?919eb900d58d99fb25aa1bd78df3fe5b.jpg
ovakav nacin zapisa imena nije po standardima

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
U meniju biramo Potrosaci, te kreiranje potrosaca
Unesemo ime ili prezime ili oboje u formatu malo-velko slovo ili bilo koja druga kombinacija velikih i malih slova koja nije po konvenciji (ili da sve budu velika ili sve mala slova ili prvo slovo veliko ostala mala)
Potrosac ce biti uspjesno spasen u bazu podataka

**Comment by aklacar1** [comment]
#44  i #43
