### ISSUE TITLE
Izmjena potroosaca- Gubljenje podatka o sifri vodomjera

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#74]
Komponenta: JKP Vodovod i Kanalizacija desktop
Commit ID: 9ac7199

Opis problema:
Ukoliko izaberemo potrosaca za izmjenu koji je tip potrosaca "sa vodomjerom" i ako mu promjenimo tip u "pausalni", a potom vratimo u "sa vodomjerom" podatak o sifri vodomjera se nece nalaziti u polju za sifru vodomjera. Ovo moze stvarati problem ukolko osoba koja koristi program greskom projeni tip i zeli da vrati stari tip ne moze doci do podatka o sifri vodomjera osim ukolko ne odabere ponovo potrosaca cime bi se izgubile promjene u drugim poljima koje je mozda unjela. 

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
U meniju biramo Potrosaci, te izmjena potrosaca
Odaberemo potrosaca koji je tip potrosaca "sa vodomjerom"
Promjenimo mu tip u "pausalni"
Nakon toga varatimo u "sa vodomojerom" 
U polju Sifra vodomjera vise nece pisati sifra vodomjera
Potrosac ce biti uspjesno spasen u bazu podataka

**Comment by azramahmutovic** [comment]
Ispravljeno
šifra vodomjera se ne briše, a ako se odabere tip "paušalni" i klikne izmijeni, šifra se zanemaruje
commit ef21cbbca6e9b4abb87a3b9809ce5be4f44b1d85
