### ISSUE TITLE
"NULL" polje u izmjeni ocitanja

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#75]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 2ac7b393be5e00fad829aadd61b2bf28b37dda34

Opis problema:
Moguće je odabrati ocitanje za izmjenu vodomjera bez broja, kao neka NULL vrijednost. Javlja se greska, ali mislim da se ne bi trebalo moci odabrati uopce ovo sto sam uspio selektovati.
http://i.imgur.com/L2TLukf.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Ocitanja, pa onda Izmijeni.
Odabir vrijednosti izmedju ponudjenih sifri vodomjera.
Klik na Izmijeni.

**Comment by aklacar1** [comment]
Nisam bio siguran ispocetka tacno zbog cega se pojavljuju ove null vrijednosti, ali sam ubrzo primjetio da su to zapravo "Pausalci" koji se ne bi ni trebali pojavljivati u ocitanjima.

**Comment by unReaLaneS** [comment]
Popravljeno u commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae
