### ISSUE TITLE
Prazan MessageBox error pri izmjeni ocitanja

### ISSUE THREAD

**Issue by dinohurem** [SoftverInzenjeringETFSA/SI2014Tim7#76]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199167395ac29ea4b045da0cf418f418febf

Opis problema:
Kada se ne odabere nikakvo ocitanje i krene kucati datum, pojavi se sljedeci MessageBox:
http://i.imgur.com/PtVSX2P.png

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Na početnom ekranu izabrati opciju Ocitanja, pa onda Izmijeni.
Poceti kucati datum u polju za datum.

**Comment by dinohurem** [comment]
Pravio sam ovaj issue vjerovatno kada je neko iz tima commit-ao update. Greskom sam stavio posljednji commit, ispravljeno je sada na prethodni. Moguce je da je ovaj bug ispravljen sada u update-u.

**Comment by unReaLaneS** [comment]
Popravljen bug u commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae
