### ISSUE TITLE
Ocitanja -> Izmjena : Nepostojeva sifra se moze selektovati

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#77]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: 9ac7199

Opis problema:
Kod ocitanja ako izaberemo izmjenu ocitanja mozemo u tabeli Odabir vodomjera selektovati nepostojecu sifru
http://pokit.org/get/?5f40743b99d82f155c4cc69d59e03408.jpg

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Odaberemo ocitanja i onda izmjenu ocitanja
4) Odaberemo red izmedju dvije ponudjene sifre

**Comment by unReaLaneS** [comment]
Popravljeno na commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

**Comment by aklacar1** [comment]
#75
