### ISSUE TITLE
Ocitanja->Izmjena: Javljanje Greske gdje ne bi trebala biti

### ISSUE THREAD

**Issue by IrmaJakic** [SoftverInzenjeringETFSA/SI2014Tim7#78]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID:2ac7b393be5e00fad829aadd61b2bf28b37dda34

Opis problema:
Kada se u Ocitanjima odabere izmjena ocitanja ukoliko drzimo ctrl i 2 puta odaberemo neku sifru ocitanja javlja se bug: Message Box error
http://pokit.org/get/?cc3991bee0ccf5fd640968028b642722.jpg

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Odaberemo ocitanja i onda izmjenu ocitanja
4) Drzimo Ctrl i odaberemo jednu od sifara dva puta

**Comment by unReaLaneS** [comment]
Popravljeno na commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae
