### ISSUE TITLE
Validacija JMBG-a

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#79]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Nije uradjena validacija jmbg-a na tabu za unos potrosaca i na formi za unos korisnika. 

Tab Potrosaci: http://imgur.com/BTBGsEZ
Tab Korisnici: http://imgur.com/vSUmEBa
Stanje u bazi: http://imgur.com/hyM8dQz

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Na pocetnom ekranu(tabu potrosaci) unijeti podatke i za jmbg unijeti 6666666666666
4) Kliknuti na opciju Spasi
5) Podaci se spasavaju

Ocekivan rezultat:
poruka greske o nevalidnom jmbg-u i prekid unosa podataka u bazu

Dobijeni rezultat: uspjesan unos potrosaca

**Comment by aklacar1** [comment]
http://prntscr.com/7b5hcv
http://prntscr.com/7b5hl9
http://prntscr.com/7b5hoe

Svi JMBG koje si unio su zapravo validni :) (6666666666666 je validan JMBG prema : http://jmbg.brmbrm.com/)
Validacija je uradjena ali nije 100% sigurna naravno, uradjena validacija prema : 
http://en.wikipedia.org/wiki/Unique_Master_Citizen_Number

**Comment by ensarmuratovic** [comment]
ako je ovo format jmbg-a: "DD MM YYY RR BBB K" (zanemari razmake) onda prema jmbg: 6666666666666  je DD: 66 MM:66, tj dan u mjesecu:66 i mjesec u godini:66. Izvor link koji si ti poslao:http://en.wikipedia.org/wiki/Unique_Master_Citizen_Number

**Comment by aklacar1** [comment]
Nema veze, to je nesto sto ne mogu prepraviti jer je osnova za validaciju JMBG zapravo sa te iste stranice, tj. ruby kod za validaciju koji je postavljen tamo. A nisam nigdje nasao bolju validaciju od ove, tako da tacnije ne moze :) A ujedno druga stranica online takodjer verifikuje taj JMBG kao ispravan.
