### ISSUE TITLE
Tab: Parametri za obračun

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#80]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Bespotrebne akcije na tabu za pregled i izmjenu parametara obracuna. Jednostavije bi bilo da se klikom na tab "Parametri za obracun" odmah prikazu popunjena sva polja sa parametrima a ne klikom na opciju pregledaj. Prilikom izmjene parametara i spasavanja se ne prikazuje nikakva poruka koja bi korisnika trebala obavijestiti o uspjesnom ili neuspjesnom unosu novih parametara. Puno jednostavnije bi bilo  da na formi samo postoji opcija izmjene parametara cijim odabirom se otvara forma za unos. Klikom na dugme spasi prikazuje se poruka (uspjesna/neuspjesna promjena) nakon cega se prikazuje forma za pregled parametara. 

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Odabrati opciju/tab Parametri  za obracun

Dobijeni rezultat:
Prikazuju se prazna polja: http://imgur.com/vg0o2iS

Ocekivani rezultat: 
Popunjena polja http://imgur.com/QC9XJrC
Prilikom unosa novih parametara i spasavanja, prikaz poruke (uspjesna/neuspjesna promjena), nakon cega se prikazu parametri kao na: http://imgur.com/QC9XJrC

**Comment by mkenan** [comment]
Popravljeno u commit ID: e655ffbe76b9d23a68042c66e26279bb86e37555
