### ISSUE TITLE
Komplikovana pretraga računa

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#81]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Komplikovana pretraga racuna na osnovu prikazanih polja. Bilo bi puno bolje da su rezultati pretrage odmah ispod parametara za pretragu te da se mijenjaju prilikom unosa parametara ili nekom opcijom "Pretrazi". Nije jasno koja se polja mogu ostaviti prazna jer npr. ako se unese ime i prezime nekog potrosaca koji placa pausalno usluge nema smisla unositi sifru vodomjera.
Takodjer ukoliko se ne unesu sva polja, npr ako se ostavi prazno ime i prezime a unese se datum sifra racuna i sifra vodomjera, odabirom opcije Pregledaj se ne desava nista(ne prikazuje se nikakva poruka) sto moze zbuniti korisnika(slika : http://imgur.com/EnznYDh)

Koraci za reproduciranje problema:

1) Kompajlirati aplikaciju (Run as java application)
2) Unijeti podatke i logirati se
3) Odabrati opciju/tab racuni
4) Unijeti period: 20/2010, sifra racuna: 5wef8w, sifra vodomjera : 1
5) Kliknuti na Pregledaj

Dobijeni rezultat:
Ne desi se nista.

Ocekivani rezultat:
Neka poruka koja ce korisnika obavijestiti o eventualnim obaveznim poljima ili o pretrazi bez rezultata na osnovu unesenih rezultata. Rezultati pretrage bi trebali biti ispod polja za unos parametara po kojim se pretrazuju racuni.

**Comment by aklacar1** [comment]
Pretraga je popravljena : aa3f58afe2b02e68a92bee120441622eb539dcf8 
Ali nije izmjenjen nacin pretrage
