### ISSUE TITLE
Format JMBG/lične karte pri unosu novog korisnika

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#82]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Pri unosu korisnika javlja se greška da JMBG/broj lične karte nisu validni, šta god da se unese. Unos vršen po uzoru na već postojeće korisnike u bazi.
http://postimg.org/image/ezau2t8rv/

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Otvoriti tab za unos korisnika, unijeti podatke i kliknuti na "SPASI"

**Comment by aklacar1** [comment]
http://prntscr.com/7b5t73
