### ISSUE TITLE
Izmjena dimenzija prozora

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#83]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Moguce je mijenjati velicinu prozora u kojem se nalazimo i time narusiti raspored i izgled komponenti.

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Moguce je mijenjati dimenzije Log-In prozora
3.  Logovati se u aplikaciju
4.  Moguce je mijenjati velicinu glavnog prozora

Dobijeni rezultat:
Mogucnost poremecaja izgleda aplikacije

Ocekivani rezultat:
Onemoguceno mijenjanje izgleda aplikacije

**Comment by aklacar1** [comment]
http://prntscr.com/7b5t73

**Comment by aklacar1** [comment]
Ispravljeno u : c1dfab16f9e9a6d2d5d8361c3473664738b60e30
