### ISSUE TITLE
Greška bez poruke

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#84]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema:
Na tabu/opciji Ocitanja nakon unosa datuma ocitanja, stanja vodomjera i klika na opciju Spasi prikazuje  se greska bez poruke(slika: http://imgur.com/T5J8Zzw).

Ocekuje se neka poruka koja ce objasniti korisniku problem koji je nastao.

**Comment by aklacar1** [comment]
Ako dobro vidim pretpostavljam da je odabir bio jednog od praznih polja, jer za sve ostalo bi trebalo vec da postoji neka poruka. Tako da je to vjerovatno isto kao : #75

**Comment by ensarmuratovic** [comment]
Ne, nije bio odabir nijednog polja, sto nije isto kao u slucaju #75 . Takodjer u #75  nije naglaseno da greska nema sadrzaj, tako da nije duplikat.

**Comment by aklacar1** [comment]
#78 je isti u tom slucaju

**Comment by aklacar1** [comment]
#76 za specificno Messagebox :)

**Comment by aklacar1** [comment]
Iako su duplikati, izgleda da nisu sve verzije ovog buga prepravljene kao sto je trebalo da bude, tako da cu ga reopen.

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716ef83f26d82e21ab8e068f8452ff8f8534a.
