### ISSUE TITLE
Nemogucnost vracanja na prozor za prijavu korisnika

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#85]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Nakon sto se korisnik prijavi u aplikaciju, korisniku nigdje nije omoguceno da se odjavi iz iste. S tim je onemoguceno da se loguje novi korisnik bez da se aplikacija prethodno ne ugasi.

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao korisnik bilo kojeg tipa
3.  Nije moguce odjaviti se iz aplikacije

Dobijeni rezultat:
Nemogucnost odjave iz aplikacije

Ocekivani rezultat:
Onemogucena odjava korisnika

**Comment by aklacar1** [comment]
#49
