### ISSUE TITLE
Prozor Korisnici - Uneseni podaci se ne brisu nakon odlaska sa prozora

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#86]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici - Nakon sto se unesu podaci u bilo koje polje prozora korisnici (bez obzira da li je odabrana opcija Kreiraj, Izmijeni, Izbrisi ili Pretrazi), pa zatim odabere bilo koji prozor iz glavnog menija, i potom se ponovo vrati na prozor korisnici, uneseni podaci su ostali ucitani.

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati bilo koju opciju (Kreiraj, Izmijeni ...)
5.  Unijeti podatke u bilo koje polje
6.  Odabrati neku od opcija glavnog menija, npr. Potrosaci
7.  Ponovo odabrati opciju Korisnici
8.  Uneseni podaci nisu obrisani

Dobijeni rezultat:
Uneseni podaci nisu obrisani nakon sto se napusti prozor

Ocekivani rezultat:
Kada korisnik ponovo otvara vec koristeni prozor, ocekuju se polja bez unesenih podataka

**Comment by aklacar1** [comment]
Ne vidim zasto bi ovo bio bug, nema razloga zasto bi se morala resotvati polja pri prelasku sa jednog panela na drugi.
