### ISSUE TITLE
Korisnici - Validacijske poruke ostaju i nakon napustanja prozora, pa ponovnog vracanja na isti

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#87]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici – Nakon sto se dobije neka validacijska poruka kada kreiramo novog korisnika, ona ostaje upisana bez obzira da li smo napustili taj prozor pa se ponovo vratili na isti.

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Kreiraj
5.  Kliknuti u neko od praznih polja, pa zatim u neko drugo prazno polje da se prikaze validacijska poruka
6.  Odabrati neku drugu opciju na prozoru Korisnici ili neku od opcija iz glavnog menija.
7.  Ponovo odabrati prozor Korisnici i opciju Kreiraj
8.  Validacijska poruka je jos prisutna

Dobijeni rezultat:
Validacijska poruka nije obrisana nakon sto se napusti forma

Ocekivani rezultat:
Validacijske poruke se trebaju obrisati nakon sto se napusti prozor ili kada su zadovoljeni uslovi validacije.

**Comment by aklacar1** [comment]
#86
