### ISSUE TITLE
Ocitanje vodomjera za nevalidan datum

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#88]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema:
Na tabu/opciji ocitanja moguce je unijeti ocitanje za datum koji je poslije trenutnog datuma sto je nemoguce.

Slika: http://imgur.com/X7svBzm

Dobijeni rezultat:
Uspjesno ocitanje.

Ocekivani rezultat: 
Poruka greske o nevalidnom datumu

**Comment by unReaLaneS** [comment]
Rijeseno u commit ID: f62716e.
