### ISSUE TITLE
Korisnici - Kreiraj - Prikaz validacije iako se nije izmijenilo ni jedno polje

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#89]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici – Kreiraj – Dovoljno je da samo kliknemo u bilo koje prazno polje na formi i zatim kliknemo na bilo koje drugo polje na formi, opciju na glavnom meniju ili neku drugu opciju unutar prozora Korisnici i dobicemo validacijsku poruku za polje u koje smo prvobitno kliknuli.

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati bilo koju opciju Kreiraj
5.  Kliknuti u neko od praznih polja
6.  Odabrati neku drugu opciju na prozoru Korisnici ili neku od opcija iz glavnog menija.
7.  Ponovo odabrati prozor Korisnici i opciju Kreiraj (ukoliko je korisnik kliknuo opciju da napusti prozor)
8.  Prisutna validacijska poruka za polje koje je bilo u fokusu prije nego je prozor napusten, iako nije nista uneseno u njega

Dobijeni rezultat:
Prikaz validacijske poruke iako korisnik nije nista unio niti u jedno polje i napustio je formu

Ocekivani rezultat:
Validacijske poruke se trebaju prikazivati tek nakon sto korisnik napravi bilo kakve izmjene na formi (ili na kraju kada se klikne na dugme spasi, sto ovdje nije bilo moguce)

**Comment by aklacar1** [comment]
#87
