### ISSUE TITLE
Korisnici - Kreiraj - Dodavanje korisnika bez Imena, Prezimena, Adrese ...

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#90]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici – Kreiraj – Moguce je dodati korisnika kojem nije uneseno ime, prezime, adresa ili korisnicko ime

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Kreiraj
5.  Unijeti samo prazne prostore na tastaturi u sva ili neko od polja: Ime, Prezime, Username, Adresa
6.  Unijeti ostala polja
7.  Klikunuti na dugme SPASI
8.  Korisnik je uspjesno dodan

Dobijeni rezultat:
Unosenjem praznog prostora u odredjena polja forme Korisnik – Kreiraj, moguce je zaobici validaciju

Ocekivani rezultat:
Unosenje praznog prostora bez adektvatnih podataka u navedena polja treba biti validirano kao da nista nije uneseno.

**Comment by aklacar1** [comment]
#56
