### ISSUE TITLE
Nevalidan datum zaposljavanja

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#93]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema:
Na formi korisnici moguce je kao datum zaposljavanja unijeti datum koji je poslije trenutnog. Nema smisla dodavati radnika u sistem koji ce biti za par godina zaposlen.
Slika: http://imgur.com/H0oNZc0

Dobijeni rezultat:
Uspjesan unos korisnika

Ocekivani rezultat: 
Poruka greske da se ne moze unijeti korisnik sa datumom zaposljavanja koji je poslije trenutnog.

**Comment by mkenan** [comment]
Ispravljeno u  commit ID : 6830d6faeb4f2fc477600b0c032ff2ea9235a09b
