### ISSUE TITLE
Brisanje bugova

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#94]
Kolege iz tima 7,

zasto ste obrisali prijavljene bugove ? Meni je trebalo vremena da ih napisem i istestiram a vi ih jednostavno obirsete. Ukoliko mislite da nije bug oznacite ga tako i stavite komentar, a  asistent ce odluciti da li ste upravu ili ne.

Omar Sisic

**Comment by aklacar1** [comment]
Nisam obrisao, Close and Comment, provjeri Closed Issues, sve sam stavio ili duplicate ili invalid i tamo se nalaze svi

**Comment by omarshile** [comment]
ok, izvini
