### ISSUE TITLE
Korisnici - Izmijeni - moguce je samo kliknuti na 2 razlicita polja i spasiti izmjene iako ih nismo napravili

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#95]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici – Izmijeni – Nakon pretrage korisnika, moguce je samo kliknuti na neka od ponudjenih polja da bi se aktiviralo dugme SPASI i zatim spasiti izmjene bez da smo ih napravili

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Izmijeni
5.  Pretraziti korisnike i odabrati jednog za izmjenu
6.  Kliknuti na neka 2 polja unutar forme da aktiviramo dugme SPASI
7.  Moguce je spasiti izmjene kojih nije bilo

Dobijeni rezultat:
Moguce spasiti izmjene na korisniku bez da se ista mijenjalo

Ocekivani rezultat:
Omoguciti spasavanje izmjena tek kada se izmjene i naprave

**Comment by aklacar1** [comment]
Stavio sam kao bug, ali wontfix, jer nema razloga za ispravku ovoga da prepravljamo cijeli kod sto nije uopste velika greksa, ili pak ikakva greska po mom misljenju.

**Comment by omarshile** [comment]
Greska je jer se radi prepisivanje podataka u bazi sa istim podacima bez ikakve potrebe.

Lp

**Comment by omarshile** [comment]
- dobije se zbunjujuca poruka da smo spasili izmjene a nismo ih ni napravili
