### ISSUE TITLE
Korisnici - Izmijeni - Necitljivi podaci u sekciji odabir korisnika

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#96]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Prozor Korisnici – Izmijeni – Nema teksta iznad kolona tabele sa pretrazenim korisnicima u sekciji Odabir Korisnika

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Izmijeni
5.  Pretraziti korisnike
6.  Dobili smo podatke o korisniku u jednom redu, vrlo nepregledno i bez naznake o kojim se podacima radi

Dobijeni rezultat:
Nepregledna tabla sa podacima korisnika

Ocekivani rezultat:
Pregledna tabela gdje se citko vide podaci i sta oni predstavljaju

**Comment by aklacar1** [comment]
Nije bug, veoma je jednostavno skontati sta se prikazuje : Ime,Prezime,JMBG i username
