### ISSUE TITLE
Brisanje korisnika

### ISSUE THREAD

**Issue by ensarmuratovic** [SoftverInzenjeringETFSA/SI2014Tim7#97]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Na tabu korisnici opcija brisanja ne radi kako treba. Ukoliko u username polje ukucamo: aaa i onda izbrisemo sadrzaj polja pretrage, u rezultatima pretrage se prikazu svi korisnici. Klikom na bilo koji od prikazanih korisnika u listi ne izaziva nikakvu promjenu nad prikazom odabranog korisnika(promjena boje ili bilo sta drugo) sto moze dovesti do toga da se izbrise pogresan korisnik.
Takodjer nakon brisanja bi se trebala azurirati prikazana lista automatski(nakon poruke o uspjesnom brisanju korisnika treba ukloniti iz liste korisnika).
Slika(odabran posljenji korisnik ): http://imgur.com/21GiMRq
Ista lista je prikazana i nakon brisanja korisnika. Tek nakon ponovne pretrage izbrisani korisnik se brise.

Ocekivani rezultat:
Prikaz oznacenog korisnika
Nakon brisanja automatski ukloniti iz liste korisnika

Dobijeni rezultat:
Nevidljiva selekcija korisnika
Nakon brisanja korisnika i dalje je prikazan u listi.

**Comment by aklacar1** [comment]
Popravljeno u : 35277a129bd8656d69058b2ff50d24d9e9a2eb95
