### ISSUE TITLE
Korisnici - Izbrisi - ukoliko unesemo bilo sta u polje username i kliknemo na dugme  izbrisi, dobijemo error bez teksta

### ISSUE THREAD

**Issue by omarshile** [SoftverInzenjeringETFSA/SI2014Tim7#98]
Komponenta: 
JKP Vodovod i Kanalizacija desktop

Commit ID:  
bb0e5cac45

Opis Problema:
Korisnici - Izbrisi - ukoliko unesemo bilo sta u polje username i kliknemo na dugme 
izbrisi, dobijemo error bez teksta

Koraci za reproduciranje problema:
1.  Kompajlirati aplikaciju (Run as java application)
2.  Prijaviti se u aplikaciju kao admin
3.  Kliknuti na opciju Korisnici u glavnom meniju
4.  Odabrati opciju Izbrisi
5.  Unijeti bilo sta u polje username
6.  Kliknuti dugme Izbrisi

Dobijeni rezultat:
Prikazana poruka bez teksta

Ocekivani rezultat:
Prikazana poruka sa opisom problema

**Comment by azramahmutovic** [comment]
Ispravljeno
dodana poruka da se izabere korisnik iz liste
commit 127367943227f12436565a0b3dabb2bd0782ce74
