### ISSUE TITLE
Nepoklapanje SRS v1.1 i aplikacije kod pretrage potrošača pri njihovoj izmjeni

### ISSUE THREAD

**Issue by ghost** [SoftverInzenjeringETFSA/SI2014Tim7#99]
Komponenta: JKP Vodovod i Kanalizacija desktop

Commit ID: bb0e5cac45f01fadbfae2afe4829398aa4b231ae

Opis problema: 
Parametri pretrage pri modifikaciji potrošača se ne podudaraju u SRS v1.1 i aplikaciji.
U SRS v1.1 su navedeni ulazi ime, prezime i jmbg, a u aplikaciji ime i jmbg
SRS v1.1: http://postimg.org/image/wpit2hrdx/
Aplikacija: http://postimg.org/image/f2rywd265/ 

Koraci za reproduciranje problema:

Kompajlirati aplikaciju (Run as java application)
Unijeti podatke i logirati se
Otvoriti tab "Potrošači" i izabrati opciju "IZMIJENI".

**Comment by aklacar1** [comment]
Popravljeno u : aa3f58afe2b02e68a92bee120441622eb539dcf8
